[Proxy Group]

PROXY = fallback,A-主用-vl-reality,A-备用-vm-argo,A-备用-vm-ws,A-备用-anytls,B-备用-long,url=http://www.gstatic.com/generate_204,interval=300,timeout=3

A-主用-vl-reality = fallback,VPS-US,use=true,policy-regex-filter=^vl-reality-Front-VPS\.US$,url=http://www.gstatic.com/generate_204,interval=300,timeout=3
A-备用-vm-argo = fallback,VPS-US,use=true,policy-regex-filter=^vm-argo-Front-VPS\.US$,url=http://www.gstatic.com/generate_204,interval=300,timeout=3
A-备用-vm-ws = fallback,VPS-US,use=true,policy-regex-filter=^vm-ws-Front-VPS\.US$,url=http://www.gstatic.com/generate_204,interval=300,timeout=3
A-备用-anytls = fallback,VPS-US,use=true,policy-regex-filter=^anytls-Front-VPS\.US$,url=http://www.gstatic.com/generate_204,interval=300,timeout=3
A-手动选择 = select,VPS-US,use=true,policy-regex-filter=Front-VPS\.US

B-美国 = url-test,long,use=true,policy-regex-filter=美国,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50,timeout=3
B-日本 = url-test,long,use=true,policy-regex-filter=日本,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50,timeout=3
B-备用-long = fallback,B-美国,B-日本,url=http://www.gstatic.com/generate_204,interval=300,timeout=3
B-手动选择 = select,long,use=true,policy-regex-filter=美国|日本

AI = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
YouTube = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
Telegram = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
GitHub = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
Google = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
Twitter = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY
GlobalMedia = select,PROXY,B-备用-long,B-美国,B-日本,B-手动选择,DIRECT,policy-select-name=PROXY

Apple = select,DIRECT,PROXY,B-备用-long,B-手动选择,policy-select-name=DIRECT
Microsoft = select,DIRECT,PROXY,B-备用-long,B-手动选择,policy-select-name=DIRECT
NAS服务 = select,DIRECT,PROXY,B-备用-long,B-手动选择,policy-select-name=DIRECT
Domestic = select,DIRECT,PROXY,policy-select-name=DIRECT
LAN = select,DIRECT,policy-select-name=DIRECT

Final = select,PROXY,DIRECT,B-备用-long,B-手动选择,policy-select-name=PROXY
